name: Trigger Jenkins Job from GitHub Actions

on:
  push:
    branches:
      - TestedBranch # Trigger on push to the main branch

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest

    steps:
      - name: Get Jenkins Crumb
        id: get-crumb
        run: |
          CRUMB=$(curl -s "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json" | jq -r '.crumb')
          echo "::set-output name=crumb::$CRUMB"

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}/build?token=${{ secrets.JENKINS_AUTH_TOKEN }}" \
            -H "Jenkins-Crumb: ${{ steps.get-crumb.outputs.crumb }}"
