name: Deploy Java Hello App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Step 3: Build the WAR file using Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Verify if the WAR file exists
      - name: Verify if WAR file exists
        run: ls -l target/

      # Step 5: Create webapps directory on remote host if not exists
      - name: Ensure webapps directory on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /var/lib/tomcat9/webapps/
            sudo chown tomcat:tomcat /var/lib/tomcat9/webapps/

      # Step 6: Deploy to EC2 via rsync
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
        with:
          source: target/java-hello-app.war
          target: /var/lib/tomcat9/webapps/

      # Step 7: Restart Tomcat on EC2
      - name: Restart Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart tomcat9
