name: Deploy Java App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the files
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Step 3: Build the WAR file using Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Ensure correct permissions on the target directory
      - name: Set Permissions on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /var/lib/tomcat9/webapps/
            sudo chown -R ${{ secrets.USERNAME }}:$${{ secrets.USERNAME }} /var/lib/tomcat9/webapps/
            sudo chmod -R 775 /var/lib/tomcat9/webapps/

      # Step 5: Deploy WAR to Server using easingthemes/ssh-deploy
      - name: Deploy WAR to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
        with:
          source: target/java-hello-app-1.0-SNAPSHOT.war
          target: /var/lib/tomcat9/webapps/

      # Step 6: Restart Tomcat on EC2
      - name: Restart Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: sudo systemctl restart tomcat9
