name: Deploy Java Hello App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Step 3: Build the WAR file using Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR1 }}
        with:
          source: target/java-hello-app.war
          target: ${{ secrets.TARGET_DIR1 }}

      # Step 5: Execute remote SSH commands to install Tomcat and restart the server
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y tomcat9
            sudo systemctl restart tomcat9
