name: Deploy Java App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Step 3: Build the WAR file using Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Rename the WAR file
      - name: Rename WAR file
        run: mv target/java-hello-app-1.0-SNAPSHOT.war target/java-hello-app.war

      # Step 5: List contents of the target directory to verify the WAR file exists
      - name: Verify WAR file exists
        run: ls -l target/

      # Step 6: Create SSH private key file
      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

      # Step 7: Use rsync from GitHub runner to transfer WAR file to EC2
      - name: Rsync WAR file to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_rsa" target/java-hello-app.war ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/var/lib/tomcat9/webapps/

      # Step 8: Restart Tomcat on EC2
      - name: Restart Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: sudo systemctl restart tomcat9
